import os
import time  # ✅ Added for unique filenames
from flask import request, jsonify
from werkzeug.utils import secure_filename
from config.db import image_db, report_db
from ml_model.plant_yolo_model import predict_disease_yolo

UPLOAD_FOLDER = "uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

def save_image_metadata(image_data):
    images = image_db["images"]
    images.insert_one(image_data)
    print("[SUCCESS] Image metadata stored.")

def process_image():
    if "image" not in request.files:
        return jsonify({"error": "No image uploaded"}), 400

    file = request.files["image"]
    if file.filename == "":
        return jsonify({"error": "Empty file name"}), 400

    # ✅ FIX: Generate a UNIQUE filename using a timestamp
    timestamp = int(time.time()) 
    filename = f"{timestamp}_{secure_filename(file.filename)}"
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    file.save(filepath)

    # Run YOLO model
    result = predict_disease_yolo(filepath)

    if "error" in result:
        return jsonify(result), 503

    # ✅ Annotated image path is now unique and permanent
    image_data = {
        "filename": filename,
        "filepath": filepath,
        "detections": result["detections"],
        "annotated_image": result["annotated_image"]
    }

    save_image_metadata(image_data)

    for detection in result["detections"]:
        report_entry = {
            "image_filename": filename,
            "disease": detection["disease"],
            "confidence": detection["confidence"],
            "recommendation": "To be generated by Agentic AI"
        }
        report_db["reports"].insert_one(report_entry)

    return jsonify({
        "message": "Image processed successfully",
        "detections": result["detections"],
        "annotated_image": result["annotated_image"],
        "filename": filename  # ✅ Pass unique filename back to frontend
    }), 200