import os
import time
from flask import request, jsonify
from werkzeug.utils import secure_filename
from config.db import image_db, report_db
from ml_model.plant_yolo_model import predict_disease_yolo

UPLOAD_FOLDER = "uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

def process_image():
    if "image" not in request.files:
        return jsonify({"error": "No image uploaded"}), 400

    file = request.files["image"]
    if file.filename == "":
        return jsonify({"error": "Empty file name"}), 400

    # Unique Filename
    timestamp = int(time.time()) 
    filename = f"{timestamp}_{secure_filename(file.filename)}"
    filepath = os.path.join(UPLOAD_FOLDER, filename)
    file.save(filepath)

    # Run YOLO (Now returns Base64)
    result = predict_disease_yolo(filepath)

    # ✅ Save Base64 to Database (So History works!)
    # Note: We are saving the actual image string to MongoDB.
    report_entry = {
        "image_filename": filename,
        "annotated_image": result["annotated_image"], # ✅ Saved for History
        "detections": result["detections"],
        "recommendation": "To be generated by Agentic AI",
        "timestamp": timestamp
    }
    
    # Save to both collections if needed, or just reports
    report_db["reports"].insert_one(report_entry)

    return jsonify({
        "message": "Image processed successfully",
        "detections": result["detections"],
        "annotated_image": result["annotated_image"], # ✅ Send to Frontend
        "filename": filename 
    }), 200